apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r1r5za6qo-python 
  janus-idp.io/tekton: r1r5za6qo-python
  backstage.io/kubernetes-id: r1r5za6qo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r1r5za6qo-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml